Feature/f04
reactif974/crazee-burger pull request #4
Opened 2022-11-17 18:20 UTC by reactif974

2022-11-19 12:47 UTC, vileaddev requested changes
Tout est bon sauf le côté overkill. On considère que quelque chose est overkill ou non en fonction de la situation du code actuelle ou celle très imminente. Dans les deux cas, les idées que tu as eu pour Icon sont un peu trop overkill et vont devenir difficile à maintenir. Essaie de rebifurquer sur quelque chose de plus simple car sinon c'est ajouter de la complexité "gratuitement"

2022-11-19 12:47 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
>          // get name param in url
Retirer ce commentaire car la ligne de code juste en dessous est suffisamment explicite.

2022-11-19 12:47 UTC, vileaddev commented on src/components/pages/reusable-ui/Icon.js
> +export default function Icon({iconName, iconClassName}) {
Ici, c'est un peu overkill de faire ça, perso, j'aurai éviter et je serais rester sur quelque chose de plus simple 😕

2022-11-19 12:47 UTC, vileaddev commented on src/components/pages/reusable-ui/Input.js
> +            <Icon iconName={iconName} iconClassName={iconClassName}/>
Envoie directement l'icon "BsPersonCircle" (ou autre) en props de Icon.  Sinon, c'est de l'overkill pour le moment #yagni

2022-11-19 12:47 UTC, vileaddev commented on src/components/pages/reusable-ui/NavBar.js
> +            <div className="user-panel">
toute la div à partir de celle contenant la className "user-panel" mérite son propre composant. C'est trop gros à ce stade là, regarde le CSS qui lui est associé 😵😵‍💫

2022-11-19 12:47 UTC, vileaddev commented on src/components/pages/reusable-ui/NavBar.js
> +    .user-panel {
ici, c'est hyper gros, crée son propre composant

2022-11-21 17:02 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
>          // get name param in url
ok supprimé

2022-11-21 17:03 UTC, reactif974 commented on src/components/pages/reusable-ui/Icon.js
> +export default function Icon({iconName, iconClassName}) {
j'ai supprimé du coup mon composant Icon et tout refactoré les composants qui l'utilisaient

2022-11-21 17:04 UTC, reactif974 commented on src/components/pages/reusable-ui/Input.js
> +            <Icon iconName={iconName} iconClassName={iconClassName}/>
voir refacto

2022-11-21 17:15 UTC, reactif974 commented on src/components/pages/reusable-ui/NavBar.js
> +            <div className="user-panel">
je viens de créer un composant UserProfil qui comprend toute la div user-panel

2022-11-22 19:28 UTC, vileaddev approved these changes
Deux corrections à ajuster et après tu peux re-git commit puis re git push.

Et après dans la volée, tu peux merge ta PR 😉

2022-11-22 19:28 UTC, vileaddev commented on src/components/pages/login/LoginPage.js
> +      <div className="logo-container">
Essayer de faire passer la className dans Logo car il a déjà un container.

2022-11-22 19:28 UTC, vileaddev commented on src/components/pages/reusable-ui/Input.js
>                  onChange={handleChange}
```suggestion
                onChange={onChange}
```

2022-11-23 10:21 UTC, reactif974 commented on src/components/pages/login/LoginPage.js
> +      <div className="logo-container">
je viens de me rendre compte que j'ai mis cette classe ici car je modifie le scale du logo de la navBar et pas directement dans le composant LOGO utilisé lui dans LoginPage et OrderPage.

2022-11-23 10:33 UTC, vileaddev commented on src/components/pages/login/LoginForm.js
> +    const onChange = (event) => {
remet handleChange, je t'explique ce soir

2022-11-23 10:33 UTC, vileaddev commented on src/components/pages/login/LoginForm.js
> +                onChange={onChange}
onChange={handleChange}

2022-11-23 10:33 UTC, vileaddev commented on src/components/pages/reusable-ui/Input.js
> +                onChange={onChange}
conserve onChange={onChange}

2022-11-23 10:34 UTC, reactif974 commented on src/components/pages/reusable-ui/Input.js
>                  onChange={handleChange}
modification faite

2022-11-23 10:36 UTC, reactif974 commented on src/components/pages/reusable-ui/Input.js
> +                onChange={onChange}
ok je le conserve

2022-11-23 11:09 UTC, merged