Feature/f05
reactif974/crazee-burger pull request #5
Opened 2022-11-23 22:12 UTC by reactif974

2022-12-04 12:06 UTC, vileaddev requested changes
Attention à ton composant OrderPage qui commence à gérer trop de complexité ☝️ Découpe et plus petit composant :)

2022-12-04 12:06 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    const [menuFake, setMenuFake] = useState(fakeMenu2)
```suggestion
    const [menu, setMenu] = useState(fakeMenu2)
```

Quand le est **défini**, il s'appelle bien "menu" mais il est **initialisé** avec un jeu de donné fake.

2022-12-04 12:06 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +                        return <div key={menu.id} className="grille-item"><MenuCard {...menu} /></div>
Soit tu l'appelles MenuCard (spécifique) est là le composant va "vivre" dans "components/pages/order/Main"

Soit tu l'appelles Card (générique) il va vivre dans reusable-ui mais du coup là, va falloir avoir des noms de props génériques aussi

2022-12-04 12:06 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +        .menu-container {
à partir de ce CSS, tu devrais déjà te dire "oulah... ça commence à en faire des lignes CSS... 😣" et avoir le réflexe de faire autre chose en conséquence 😉

2022-12-04 12:06 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +            grid-template-columns: repeat(4, 240px);
```suggestion
            grid-template-columns: repeat(4, 1fr);
```

si tu sais que toutes tes MenuCard ont la même taille, 1fr peut suffir puisque la taille/ width de la MenuCard est normalement précisée "dans" MenuCard.

Ce n'est pas de la responsabilité de OrderPage que de décider de la taille de MenuCard. 

Mais c'est de la responsabilité de OrderPage que de décider du layout (disposition des éléments à l'intérieur de OrderPage) et donc de la disposition des MenuCards

2022-12-04 12:06 UTC, vileaddev commented on src/components/pages/reusable-ui/MenuCard.js
> +            <PriceContainer price={price} />
Pourquoi pas en effet :)

2022-12-04 20:35 UTC, videvjs commented on src/components/pages/reusable-ui/PriceContainer.js
> +export default function PriceContainer({price}) {
C'est beaucoup trop spécifique, il ne peut pas être dans reusable/ui

2022-12-05 11:03 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
> +    const [menuFake, setMenuFake] = useState(fakeMenu2)
modification effectué

2022-12-05 11:03 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
> +                        return <div key={menu.id} className="grille-item"><MenuCard {...menu} /></div>
création d'un composant MenuCard

2022-12-05 11:04 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
> +        .menu-container {
création d'un composant MenuCard avec le CSS associé

2022-12-05 11:04 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
> +            grid-template-columns: repeat(4, 240px);
effectivement je n'avais pas vu cette possibilité.

2022-12-05 11:05 UTC, reactif974 commented on src/components/pages/reusable-ui/PriceContainer.js
> +export default function PriceContainer({price}) {
déplacement du composant PriceContainer dans pages/order/main

2022-12-05 11:05 UTC, reactif974 commented on src/components/pages/reusable-ui/MenuCard.js
> +            <PriceContainer price={price} />
:)

2022-12-08 18:50 UTC, videvjs approved these changes
Quelques changement après c'est bon, tu peux merge

2022-12-08 18:50 UTC, videvjs commented on src/components/pages/order/main/MenuCard.js
> +export default function MenuCard() {
```suggestion
export default function Menu() {
```

MenuCard pourrait faire croire à une Card dans le Menu 😕

2022-12-08 18:50 UTC, videvjs commented on src/components/pages/reusable-ui/Card.js
> +    const shortTitle = title.length > 20 ? title.substring(0,16) + "..." : title
Je sais pas si tu as vu les vidéos du F05 mais la propriété CSS "ellipsis" suffisait largement. Tu peux garder ça mais alors créer une fonction dans un fichier utils à part et range s'y une fonction shortenString(). Dans Card.js, tu importes cette fonction en faisant passer en paramètre "title" et le résultat sera stockée dans une variable à shortTitle que tu pourras ensuite projeter dans ton affichage au niveau du h2.

2022-12-08 18:50 UTC, videvjs commented on src/utils/number/format.js
> +export function formatPrice(priceToFormat) {
J'ai rajouté une autre fonction formatPrice dans le .zip de ton espace. Je te conseille de prendre cette nouvelle fonction, elle nous servira après :)

2022-12-08 18:51 UTC, videvjs requested changes
Quelques changement à faire avant de pouvoir merge mais t'y es presque.

2022-12-09 11:03 UTC, reactif974 commented on src/components/pages/reusable-ui/Card.js
> +    const shortTitle = title.length > 20 ? title.substring(0,16) + "..." : title
correction faite avec un text-overflow: ellipsis , un white-space: nowrap et un overflow: hidden

2022-12-09 11:03 UTC, reactif974 commented on src/utils/number/format.js
> +export function formatPrice(priceToFormat) {
fonction ajouté

2022-12-09 11:04 UTC, reactif974 commented on src/components/pages/order/main/MenuCard.js
> +export default function MenuCard() {
changement de naming fait

2022-12-09 11:04 UTC, merged