Feature/f06
reactif974/crazee-burger pull request #6
Opened 2022-12-09 15:32 UTC by reactif974

create switch admin mode with toast notify

2022-12-09 17:20 UTC, videvjs requested changes
Quelques commentaires

2022-12-09 17:20 UTC, videvjs commented on src/components/pages/reusable-ui/ToggleButton.js
> +        onClick={!isChecked ? toastNotify : null}
le "if" ne se gère pas dans l'interpolation mais plutôt dans la fonction toastNotify()

2022-12-09 17:20 UTC, videvjs commented on src/components/pages/reusable-ui/ToggleButton.js
> +  const toastNotify = () => {
```suggestion
  const showToastNotification = () => {
```

2022-12-09 17:23 UTC, videvjs requested changes

2022-12-09 17:23 UTC, videvjs commented on src/components/pages/reusable-ui/ToggleButton.js
> +      <NavbarRightSideIncomplet />
ah mais, il fallait utiliser le style de navbarrightside 😅

2022-12-09 17:38 UTC, reactif974 commented on src/components/pages/reusable-ui/ToggleButton.js
> +        onClick={!isChecked ? toastNotify : null}
changement fait

2022-12-09 17:39 UTC, reactif974 commented on src/components/pages/reusable-ui/ToggleButton.js
> +  const toastNotify = () => {
modifié

2022-12-09 17:40 UTC, reactif974 commented on src/components/pages/reusable-ui/ToggleButton.js
> +      <NavbarRightSideIncomplet />
dit moi si c'est ok, j'ai fait un composant toast ou je reprend le style de NavbarRightSide

2022-12-10 13:27 UTC, reactif974 commented on src/components/pages/reusable-ui/ToggleButton.js
> +      <NavbarRightSideIncomplet />
je viens de corriger, je clôture le commentaire

2022-12-12 17:55 UTC, videvjs requested changes

2022-12-12 17:55 UTC, videvjs commented on src/components/pages/reusable-ui/NavBar.js
> +      <div className="user-profile-right-side">
OPTIONNEL : Là, c'est les goûts et les couleurs mais perso, j'aurai ranger dans un composant à part "user-profile-right-side", d'où mon NavbarRightSide dans les vidéos. Persp, je trouve ça plus propre et clair. Mais encore une fois, c'est optionnel.

2022-12-12 17:55 UTC, videvjs commented on src/components/pages/reusable-ui/NavbarRightSideIncomplet.js
> +export default function NavbarRightSideIncomplet() {
Du coup, plus besoin de l'appeler comme ça. Autant l'appeler ToastAdmin, qui est plus explicite.

2022-12-12 17:55 UTC, videvjs commented on src/components/pages/reusable-ui/ToggleButton.js
> +      <NavbarRightSideIncomplet />
Du coup, ToastAdmin ici.

2022-12-13 10:05 UTC, reactif974 commented on src/components/pages/reusable-ui/NavBar.js
> +      <div className="user-profile-right-side">
Tu as raison j'ai refacto le code et c'est beaucoup plus propre

2022-12-13 10:07 UTC, reactif974 commented on src/components/pages/reusable-ui/NavbarRightSideIncomplet.js
> +export default function NavbarRightSideIncomplet() {
j'avais supprimé ce composant et j'ai crée un composant Toast réutilisable

2022-12-13 10:08 UTC, reactif974 commented on src/components/pages/reusable-ui/ToggleButton.js
> +      <NavbarRightSideIncomplet />
Du coup j'importe maintenant le composant Toast dans NavBarRightSide.js

2022-12-13 10:10 UTC, merged