Feature/f07
reactif974/crazee-burger pull request #7
Opened 2022-12-16 17:42 UTC by reactif974

create panel admin

2022-12-20 18:14 UTC, videvjs requested changes

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/OrderPage.js
> +  const contextValue = {
```suggestion
  const globalContextValue = {
```
OPTIONNEL : préférer peut-être globalContextValue au cas où tu aurais un autre context qui vient

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/OrderPage.js
> +    updateIsModeAdmin: setIsModeAdmin,
tu peux en effet donner un nom différent mais pourquoi le faire si on set déjà que le rôle d'un setter de state c'est d'updater la valeur du state ? setIsModeAdmin c'est déjà très bien

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/OrderPage.js
> +          {/* TODO: basket container */}
```suggestion
          {/* @TODO: basket container */}
```

C'est la coutume chez les dev qui veut ça.

2022-12-20 18:14 UTC, videvjs commented on src/context/GlobalContext.js
> +  isPanelReduce: false,
isPanelHidden
```suggestion
  isPanelReduce: false,
```

ou encore, tu as aussi : "isPannelCollapsed"

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +    <BlocAdminPanelContentStyled isPanelReduce={isPanelReduce}>
je montrerai lors du live AMA une manière plus courante de gérer ça

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          className={`tabs tabs-one ${panelTabIndex === 1 && "is-active-tab"}`}
ici, la className est trop "encombrée". Extrait toute cette logique de l'affichage et envoie là dans la box "comportements" et gère le dedans.

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          onClick={() => hideAndShowAdminPanelContent()}
```suggestion
          onClick={hideAndShowAdminPanelContent}
```

Puisque tu n'envoies pas de paramètres / variables à hideAndShowAdminPanelContent

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          className={`tabs tabs-two ${panelTabIndex === 2 && "is-active-tab"}`}
ça aussi, extrait le de l'affichage, et gère le dans "comportements"

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          onClick={() => toggleTab(2)}
là, tu vois, t'es obligé en effet de passer par une fonction fléchée puisque tu appelles toggleTab **avec le paramètre 2** 💯

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          className={`tabs tabs-three ${
pareil ici.

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/BlocTabs.js
> +  .tabs-one {
rajoute des espace, pour quelqu'un qui est nouveau à ton code, ça fait un gros bloc monolithe à décrypter, c'est pas forcément agréable 😕

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/PanelAdminTabs.js
> +      <div className={isModeAdmin ? "showAdminPanel" : "closeAdminPanel"}>
gère le à la ligne 9 en créant une variable

const bloc-tab-container = isModeAdmin ? "showAdminPanel" : "closeAdminPanel"

et plus bas, dans l'affichage tu envoies dans le className la variable "bloc-tab-container"

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/adminPanel/PanelAdminTabs.js
> +  .showAdminPanel {
ajouter un espace entre l.41 et l.42

Le CSS (surtout le CSS) lui aussi mérite d'être clair dans sa lisibilité.

2022-12-20 18:14 UTC, videvjs commented on src/components/pages/order/main/Menu.js
> +        })}
```
{menu.map((menu) => 
            <div key={menu.id} className="grille-item">
              <Card {...menu} />
            </div>
)}
```

ici, tu peux simplifier le code pour le rendre moins lourd dans sa lisibilité

2023-02-05 18:20 UTC, reactif974 commented on src/components/pages/order/OrderPage.js
> +  const contextValue = {
mieux je suis d'accord

2023-02-05 18:30 UTC, reactif974 commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +    <BlocAdminPanelContentStyled isPanelReduce={isPanelReduce}>
ok ça marche

2023-02-05 18:34 UTC, reactif974 commented on src/components/pages/order/adminPanel/BlocTabs.js
> +          onClick={() => hideAndShowAdminPanelContent()}
effectivement

2023-02-05 18:41 UTC, reactif974 commented on src/components/pages/order/adminPanel/PanelAdminTabs.js
> +      <div className={isModeAdmin ? "showAdminPanel" : "closeAdminPanel"}>
oui effectivement plus propre

2023-02-14 17:46 UTC, vileaddev requested changes

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +  const [panelTabIndex, setPanelTabIndex] = useState(1);
```suggestion
  const [panelTabIndex, setPanelTabIndex] = useState("add");
```

As-tu plus explicite qu'un nombre qui est assez vague ? Quand tu nomme quelque chsoe essaie au maximum de t'exploigner de l'implémentation technique et plus vers le "métier" et le "concret". Le test c'est : "même un non technos sans background technique est censé comprendre". Ici, "panelTabIndex" avec une initialisation à 1 c'est un peu trop technique mais "panelTabIndex" avec "add" on visualise mieux tout de suite.

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +  const [isPannelCollapsed, setIsPannelCollapsed] = useState(false);
Oui, très explicite 💯

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +          {/* @TODO: basket container */}
```suggestion
          {/* Keep this basket container for the basket feature ticket */}
```

ici, ce n'est pas un @TODO à proprement parler car il n'y a aucune action requise. C'est un simple commentaire pour signaler aux autres dev qu'il ne faut pas te rappeler dans la PR de le supprimer.

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +  const tabSelected = tabs.find((tab) => tab.index === panelTabIndex);
```suggestion
  const tabSelected = tabs.find((tab) => tab.index === panelTabIndex);
```
essaie d'abstraire cette instruction dans une fonction à part : "tabs.find((tab) => tab.index === panelTabIndex)". On ne veut pas connaitre l'**implémentation**. On veut juste l'**intention**.

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +        {panelTabIndex === tabSelected.index && tabSelected.content}
```suggestion
        {tabSelected && tabSelected.content}
```

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +  display: ${(props) => (props.isPannelCollapsed ? "none" : "block")};
cette gestion par le Styled-Component rend compliqué la maintenance de cette partie-là du code. Privilégie plutôt une ternaire à dans le composant parent pour faciliter la lisibilité et la maintenance de ton code.

2023-02-14 17:46 UTC, vileaddev commented on src/components/pages/order/adminPanel/PanelAdminTabs.js
> +  const bloc_tab_container = isModeAdmin ? "showAdminPanel" : "closeAdminPanel";
```suggestion
  const blocTabContainer = isModeAdmin ? "showAdminPanel" : "closeAdminPanel";
```

C'est une variable classique, donc pourquoi vouloir changer la notation en snake case ? Pas besoin ici. Le Camel case suffit largement. Il faut éviter autant que possible de multiplier différents types de notation dans un même projet.

2023-03-11 07:37 UTC, reactif974 commented on src/components/pages/order/adminPanel/PanelAdminTabs.js
> +  const bloc_tab_container = isModeAdmin ? "showAdminPanel" : "closeAdminPanel";
ok

2023-03-12 18:31 UTC, vileaddev reviewed
quelques changement pour rendre ton code plus scalable et plus facile à maintenir pour toi à l'avenir

2023-03-12 18:31 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +    } else if (panelTabIndex === "edit") {
```suggestion
    } if (panelTabIndex === "edit") {
```

2023-03-12 18:31 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocAdminPanelContent.js
> +    } else {
retirer ce dernier else, il ne sert à rien du tout. Teste, tu verras que tu as le même rendu UI et comportement.

2023-03-12 18:31 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocTabs.js
> +    if (isPannelCollapsed) {
tu peux retirer cette condition et exécuter l'instruction quelque soit la situation il me semble. Faudrait tester.

2023-03-12 18:31 UTC, vileaddev commented on src/components/pages/order/adminPanel/getTabsConfig.js
> +      onClick: () => setIsPannelCollapsed(!isPannelCollapsed),
tu peux retirer le onClick dans les trois objets pour l'exécuter dans le map de ton tabs dans le fichier BlocTabs.js
=> ça allège ton fichier de config et rend plus maintenable / scalable ton code sur la partie Admin

2023-03-13 13:18 UTC, vileaddev requested changes

2023-03-13 13:18 UTC, vileaddev commented on src/components/pages/order/adminPanel/BlocTabs.js
> +              onClick={
```suggestion
              onClick={selectTab}
```

créé selectTab et regroupe tout ça là haut pour faire encore plus clean 😉  mais sinon, superbe, c'est encore plus malin que ce que moi j'avais trouvé 😳

2023-03-13 13:18 UTC, vileaddev commented on src/components/pages/order/adminPanel/getTabsConfig.js
> +      className: isPannelCollapsed
le className aussi en fait tu peux le sortir ✅

2023-03-13 18:04 UTC, reactif974 commented on src/components/pages/order/adminPanel/BlocTabs.js
> +              onClick={
merci @vileaddev ça fait plaisir !!

2023-03-13 18:44 UTC, reactif974 commented on src/components/pages/order/adminPanel/getTabsConfig.js
> +      className: isPannelCollapsed
ça me parait difficile a faire @vileaddev car le retour des conditions ternaire c'est un coup un className avec tabs-one , l'autre tabs-two ect ...

2023-03-13 19:08 UTC, merged