FO8
reactif974/crazee-burger pull request #8
Opened 2023-03-14 11:22 UTC by reactif974

2023-03-21 18:32 UTC, vileaddev requested changes

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/login/LoginForm.js
> +          variant="normal"
du coup en fait, limite tu peux le supprimer car par défault ton composant TextInput a en props par défaut la valeur de "normal" pour le props variant

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +    setMenus,
autant que possible on va éviter d'envoyer directement le setter dans le context si on fait des manipulation sur le state. Préférer envoyer une autre fonction resetMenu() qui elle va appeler setMenu dans ses instructions

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/adminPanel/forms/AddProductForm.js
> +  const { isSubmitSucces, setIsSubmitSucces, handleAdd } =
```suggestion
  const { isSubmitSuccess, setIsSubmitSuccess, handleAdd } =
```

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +  const [isSubmitSucces, setIsSubmitSucces] = useState(false);
```suggestion
  const [isSubmitSuccess, setIsSubmitSuccess] = useState(false);
```

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/adminPanel/forms/AddProductForm.js
> +        <div className="pics-preview"></div>
Peut être créer un composant dédié au ImagePreview ici pour faire plus propre ?

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/adminPanel/forms/AddProductForm.js
> +            <span className="succes-message">
Peut être créer un composant dédié au SubmitMessage ici pour faire plus propre ?

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/adminPanel/forms/AddProductForm.js
> +    .submit-container {
Envoyer tooooout ce CSS dans le composant SubmitMessage pour désengorger le CSS de AddProductForm

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +  const [menus, setMenus] = useState(fakeMenu.LARGE);
```suggestion
  const [menu, setMenu] = useState(fakeMenu.LARGE);
```

Pourquoi mettre un "s" à menu ? On a un seul menu pourtant. Si tu veux mettre un "s" pour indiquer qu'on parle d'un array, alors préférer [menuProducts, setMenuProducts]

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/main/Menu.js
> +          {menus?.map((menu) => (
Naming à revoir ici.

Tu n'envoie pas "un" menu, tu envoies "un produit" du menu

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/order/main/PriceContainer.js
> +      <Button text="Ajouter" type="submit" variant="add" />
On est dans le contexte de Button, un composant réutilisable. Autrement, le naming de ses props doit être générique et non spécifique. Ici, "add" est trop spécifique. On préferra des noms comme "success" ou "secondary"

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/reusable-ui/Button.js
> +  ${(props) => props.variant === "sucess" && getSucessStyle()}
```suggestion
  ${(props) => props.variant === "success" && getSuccessStyle()}
```

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/reusable-ui/Button.js
> +  ${(props) => props.variant === "refresh" && getRefreshStyle()}
à retirer.

Ici, c'est du spécifique. le but ce n'est pas de "recenser" tous les cas d'usage ici. Le but c'est de créer des cas d'usages classiques et communs.

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/reusable-ui/DeleteButton.js
> +    <DeleteButtonStyled onClick={() => handleDelete(id)}>
```suggestion
    <DeleteButtonStyled onClick={onClick}>
```
le handleDelete est trop specifique ici, tu l'as transpercé avec ton handleDelete ce qui ne le rend plus réutilisable

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/reusable-ui/Input.js
> +      <span className="icon">{Icon && Icon}</span>
```suggestion
      {Icon && <span className="icon">{Icon}</span>}
```

Faut qu'on voit ça ensemble en vocal juste après, je te ré-expliquerai ça proprement 😉

2023-03-21 18:32 UTC, vileaddev commented on src/components/pages/reusable-ui/Input.js
> +export default function Input({
```suggestion
export default function TextInput({
```

Je conseille de l'appeler TextInput car tu as mis en type="text" et par la suite, on aura SelectInput et peut etre même après CheckboxInput

2023-04-09 08:41 UTC, reactif974 commented on src/components/pages/reusable-ui/Button.js
> +  ${(props) => props.variant === "refresh" && getRefreshStyle()}
je ferais les changements soit dans la FO9 soit dans la F10

2023-04-09 08:42 UTC, merged